# Generated by Django 2.1.3 on 2018-11-14 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('garage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AFaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=64)),
                ('date', models.DateField(blank=True, null=True)),
                ('kms', models.IntegerField(blank=True, null=True)),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Entretien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kms', models.IntegerField()),
                ('date', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField()),
                ('facture', models.FileField(blank=True, null=True, upload_to='')),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.Garage')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=32)),
                ('modele', models.CharField(max_length=32)),
                ('immatriculation', models.CharField(blank=True, max_length=32, null=True)),
                ('mise_en_circulation', models.IntegerField(default='0')),
                ('visible', models.BooleanField(default=False)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='entretien',
            name='vehicule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.Vehicule'),
        ),
        migrations.AddField(
            model_name='afaire',
            name='vehicule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.Vehicule'),
        ),
    ]
