# Generated by Django 2.1.3 on 2018-11-14 12:25

from django.db import migrations, models
import garage.models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0002_auto_20181114_1308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicule',
            options={'ordering': ('marque', 'modele')},
        ),
        migrations.RemoveField(
            model_name='entretien',
            name='description',
        ),
        migrations.AlterField(
            model_name='entretien',
            name='facture',
            field=models.FileField(blank=True, null=True, upload_to=garage.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='mise_en_circulation',
            field=models.IntegerField(default=0),
        ),
    ]
